[project]
name = "prop_copilot"
version = "0.1.0"
requires-python = ">=3.10"

[tool.black]
line-length = 100
target-version = ["py311","py312","py313"]

[tool.ruff]
line-length = 100
select = ["E", "F", "W", "I", "UP"]
