name: ci

on:
  push:
  pull_request:

jobs:
  lint-and-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff==0.5.7 pyflakes

      - name: Ruff version & config
        run: |
          ruff --version
          echo "---- ruff config ----"
          ruff config

      - name: Ruff clean (drop cache)
        run: ruff clean

      - name: Ruff (lint)
        run: ruff check --output-format=github --no-cache .

      - name: Import check (best-effort)
        run: python -m pyflakes app || true
